const CropData = [
  { name: "Rice", emoji: "🌾", cat: "cereal", season: "Kharif", note: "Thrives in warm, flooded paddies with heavy rainfall." },
  { name: "Maize", emoji: "🌽", cat: "cereal", season: "Kharif", note: "Balanced soil and steady moisture suit it well." },
  { name: "Chickpea", emoji: "🫘", cat: "pulse", season: "Rabi", note: "Prefers drier, low-nitrogen ground." },
  { name: "Kidney Beans", emoji: "🫘", cat: "pulse", season: "Rabi", note: "Likes warm soil with moderate rainfall." },
  { name: "Pigeon Peas", emoji: "🌱", cat: "pulse", season: "Kharif", note: "Hardy across semi-arid fields." },
  { name: "Moth Beans", emoji: "🌱", cat: "pulse", season: "Kharif", note: "Drought-tolerant and undemanding." },
  { name: "Mung Bean", emoji: "🌱", cat: "pulse", season: "Kharif", note: "Quick-growing in warm conditions." },
  { name: "Black Gram", emoji: "🌱", cat: "pulse", season: "Kharif", note: "Warm, moderately moist soil is ideal." },
  { name: "Lentil", emoji: "🫘", cat: "pulse", season: "Rabi", note: "Cool, dry, well-drained ground suits it." },
  { name: "Pomegranate", emoji: "🍎", cat: "fruit", season: "Perennial", note: "Tolerates dry heat and varied soils." },
  { name: "Banana", emoji: "🍌", cat: "fruit", season: "Year-round", note: "Rich nitrogen and good moisture favour it." },
  { name: "Mango", emoji: "🥭", cat: "fruit", season: "Summer", note: "Warm climate with a dry spell before flowering." },
  { name: "Grapes", emoji: "🍇", cat: "fruit", season: "Winter–Spring", note: "Warm, dry seasons give the best fruit." },
  { name: "Watermelon", emoji: "🍉", cat: "fruit", season: "Zaid", note: "Warm soil and steady water during growth." },
  { name: "Muskmelon", emoji: "🍈", cat: "fruit", season: "Zaid", note: "Warm, sunny conditions with moderate water." },
  { name: "Apple", emoji: "🍎", cat: "fruit", season: "Temperate", note: "Cool hill temperatures suit orchard apples." },
  { name: "Orange", emoji: "🍊", cat: "fruit", season: "Winter", note: "Mild climate with well-drained soil." },
  { name: "Papaya", emoji: "🥭", cat: "fruit", season: "Year-round", note: "Warm, frost-free conditions year round." },
  { name: "Coconut", emoji: "🥥", cat: "fruit", season: "Perennial", note: "Coastal warmth and reliable moisture." },
  { name: "Cotton", emoji: "🧶", cat: "cash", season: "Kharif", note: "Low rain and high heat point to cotton." },
  { name: "Jute", emoji: "🧵", cat: "cash", season: "Kharif", note: "Warm, humid conditions with good rainfall." },
  { name: "Coffee", emoji: "☕", cat: "cash", season: "Perennial", note: "Acidic soil with steady rain favours coffee." },
];

export default CropData;
